services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./instance:/app/instance # Persistance de la base de données
      - ./backend:/app/backend   # Montage du code source pour le hot-reload
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend-dev
    ports:
      - "5173:5173" # Port par défaut de Vite
    volumes:
      - ./frontend:/app # Montage du code source pour le hot-reloading
      - /app/node_modules # Cache des node_modules du conteneur pour éviter l'écrasement par le montage local
    depends_on:
      - backend
    env_file:
      - ./frontend/.env # Pour VITE_API_KEY et VITE_API_URL
    environment:
      - VITE_PROXY_API_TARGET_URL=http://backend:8080
    restart: unless-stopped